- name: "node - get subnet id of VPC with region us-west-2b"
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
  register: ose_vpc_subnet

- set_fact: vpc_subnet_id="{{ item.id }}"
  when: item.availability_zone == "us-west-2b"
  with_items: "{{ ose_vpc_subnet.subnets }}"

- name: "node - create ose cluster node"
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "{{ aws_key_name }}"
    image: "{{ aws_image_id }}"
    instance_type: "{{ aws_node_instance_type }}"
    wait: yes
    group: "{{ ose_security_group_name}}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    exact_count: "{{ aws_node_count }}"
    region: "{{ aws_region }}"
    instance_tags:
      ose_type: node
      ose_node: yes
    count_tag: ose_node

- name: "node - gather EC2 instances list"
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      instance-state-name: running
      "tag:ose_type": node
  register: ose_ec2_nodes

- name: "node - set name for all the node instances"
  ec2_tag:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    resource: "{{ item.1.id }}"
    tags:
      Name: node{{ item.0 }}.{{ ose_cluster_domain }}
  with_indexed_items: "{{ ose_ec2_nodes.instances }}"

- name: "node - gather EC2 instances list"
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      instance-state-name: running
      "tag:ose_type": node
  register: ose_ec2_nodes

- name: "node - wait for SSH to come up"
  wait_for: host="{{ item.public_dns_name }}" port=22 timeout=320 state=started
  with_items: "{{ ose_ec2_nodes.instances }}"

- name: "node - adding node host to dynamcic host list"
  add_host:
    hostname: "{{ item.tags.Name }}"
    groups: "nodes"
    ansible_user: "{{ user_name }}"
    ansible_host: "{{ lookup('dig', item.public_dns_name) }}"
    public_host_name: "{{ item.public_dns_name }}"
    fixed_ip: "{{ item.private_ip_address }}"
    floating_ip: "{{ lookup('dig', item.public_dns_name) }}"
  with_items: "{{ ose_ec2_nodes.instances }}"

- set_fact: l_is_atomic_host=false

- name: "add node entry to hosts file for [nodes] section"
  lineinfile: dest="{{ host_file_path }}" state=present insertafter=^\[nodes\]
    line="{{ item.tags.Name }} openshift_hostname={{ item.tags.Name }} openshift_public_hostname={{ item.tags.Name }} openshift_public_ip={{ lookup('dig', item.public_dns_name) }}"
  with_items: "{{ ose_ec2_nodes.instances }}"
