- name: "lab - get subnet id of VPC with region us-west-2b"
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
  register: ose_vpc_subnet

- set_fact: vpc_subnet_id="{{ item.id }}"
  when: item.availability_zone == "us-west-2b"
  with_items: "{{ ose_vpc_subnet.subnets }}"

- name: "lab - create ose cluster lab"
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "{{ aws_key_name }}"
    image: "{{ aws_image_id }}"
    instance_type: "{{ aws_lab_instance_type }}"
    wait: yes
    group: "{{ ose_security_group_name}}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    exact_count: 1
    region: "{{ aws_region }}"
    instance_tags:
      ose_type: lab
      ose_lab: yes
    count_tag: ose_lab

- name: "lab - gather EC2 instances list"
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      instance-state-name: running
      "tag:ose_type": lab
  register: ose_ec2_labs

- name: "lab - set name for the single lab instance"
  ec2_tag:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    resource: "{{ item.id }}"
    tags:
      Name: lab.{{ ose_cluster_domain }}
  with_items: "{{ ose_ec2_labs.instances }}"

- name: "lab - gather EC2 instances list"
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      instance-state-name: running
      "tag:ose_type": lab
  register: ose_ec2_labs

- name: "lab - wait for SSH to come up"
  wait_for: host="{{ item.public_dns_name }}" port=22 timeout=320 state=started
  with_items: "{{ ose_ec2_labs.instances }}"

- name: "lab - find public ip"
  set_fact: public_ip="{{ lookup('dig', item.public_dns_name) }}"
  with_items: "{{ ose_ec2_labs.instances }}"

- name: "lab - adding lab host to dynamcic host list"
  add_host:
    hostname: "{{ item.tags.Name }}"
    groups: "labs"
    ansible_user: "{{ user_name }}"
    ansible_host: "{{ public_ip }}"
    public_host_name: "{{ item.public_dns_name }}"
    fixed_ip: "{{ item.private_ip_address }}"
    floating_ip: "{{ public_ip }}"
  with_items: "{{ ose_ec2_labs.instances }}"

- set_fact: l_is_atomic_host=false
