---
- name: enable redhat subscription
  redhat_subscription: state=present username={{ rhel_subs_user }} password={{ rhel_subs_pass }}

- name: update subscription pool and repos required for openshift
  command: "{{ item }}"
  with_items:
    - subscription-manager remove --all
    - subscription-manager attach --pool={{ rhel_subs_pool_int }}
    - subscription-manager repos --disable="*"
    - subscription-manager repos
        --enable="rhel-7-server-rpms"
        --enable="rhel-7-server-extras-rpms"
        --enable="rhel-7-server-ose-3.1-rpms"
        --enable="rhel-ha-for-rhel-7-server-rpms"
