---
- name: yum update all
  yum: name=* state=latest

- name: install repos
  yum: name={{ item }} state=latest
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - atomic-openshift-utils
    - docker

- name: update hostname
  hostname: name={{ inventory_hostname }}

- name: "remove cloud.cfg update_hostname entry"
  lineinfile: dest=/etc/cloud/cloud.cfg state=absent regexp=".*update_hostname"

- name: "add preserve_hostname to cloud.cfg"
  lineinfile: dest=/etc/cloud/cloud.cfg state=present line="preserve_hostname{{ ':' }} true"

- name: "update resolv.conf with local dns server"
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: set PEERNDS to no
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0 regexp="^PEERDNS=\"yes\"" line="PEERDNS=\"no\"" state=present

- name: set SELinux to permissive
  lineinfile: dest=/etc/sysconfig/selinux regexp="^SELINUX=.*" line="SELINUX=permissive"

- name: add docker insecure registry for 0.0.0.0:0
  lineinfile: dest=/etc/sysconfig/docker regexp='^OPTIONS=.*--insecure-registry.*' state=present line="OPTIONS='--insecure-registry 0.0.0.0:0 --selinux-enabled '"

- name: "enable docker service"
  service: name=docker enabled=yes
  ignore_errors: yes

