---
- name: "creating ose etcd vms"
  when: etcd_in_master == false
  os_server:
    cloud: "{{ named_cloud }}"
    name: "{{ item }}"
    state: present
    image: "{{ image_name }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor_name }}"
    security_groups: "{{ security_groups }}"
  with_sequence: count={{ ose_etcd_count }} format={{ node_start_name }}-{{ ose_etcd_name}}%d

- name: "creating ose master vms"
  os_server:
    cloud: "{{ named_cloud }}"
    name: "{{ item }}"
    state: present
    image: "{{ image_name }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor_name }}"
    security_groups: "{{ security_groups }}"
  with_sequence: count={{ ose_master_count }} format={{ node_start_name }}-{{ ose_master_name}}%d

- name: "creating ose node vms"
  os_server:
    cloud: "{{ named_cloud }}"
    name: "{{ item }}"
    state: present
    image: "{{ image_name }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor_name }}"
    security_groups: "{{ security_groups }}"
  with_sequence: count={{ ose_node_count }} format={{ node_start_name }}-{{ ose_node_name}}%d

- name: "creating ose lb vms"
  os_server:
    cloud: "{{ named_cloud }}"
    name: "{{ node_start_name }}-{{ ose_lb_name}}"
    state: present
    image: "{{ image_name }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor_name }}"
    security_groups: "{{ security_groups }}"
  when: ose_master_count > 1

- name: "creating ose dns vms"
  os_server:
    cloud: "{{ named_cloud }}"
    name: "{{ node_start_name }}-{{ ose_dns_name}}"
    state: present
    image: "{{ dns_image_name }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor_name }}"
    security_groups: "{{ security_groups }}"