---
- name: "deleting ose master vms"
  os_server:
    cloud: "{{ named_cloud }}"
    name: "{{ item }}"
    state: absent
  with_sequence: count={{ ose_master_count }} format={{ node_start_name }}-{{ ose_master_name}}%d

- name: "deleting ose node vms"
  os_server:
    cloud: "{{ named_cloud }}"
    name: "{{ item }}"
    state: absent
  with_sequence: count={{ ose_node_count }} format={{ node_start_name }}-{{ ose_node_name}}%d

- name: "deleting ose etcd vms"
  os_server:
    cloud: "{{ named_cloud }}"
    name: "{{ item }}"
    state: absent
  with_sequence: count={{ ose_etcd_count }} format={{ node_start_name }}-{{ ose_etcd_name}}%d
  when: etcd_in_master == false

- name: "deleting ose lb vms"
  os_server:
    cloud: "{{ named_cloud }}"
    name: "{{ node_start_name }}-{{ ose_lb_name}}"
    state: absent

- name: "deleting ose dns vms"
  os_server:
    cloud: "{{ named_cloud }}"
    name: "{{ node_start_name }}-{{ ose_dns_name}}"
    state: absent
