---
- name: "setup localhost for continuing OpenShift installation"
  hosts: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: "remove if any old masters in the hosts file"
      lineinfile: dest="/etc/hosts" regexp=".*{{ hostvars[item]['inventory_hostname'] }}.*" state=absent
      with_items:
        - "{{ groups.masters }}"
        - "{{ groups.lb }}"

    - name: "add masters to hosts file"
      lineinfile: dest="/etc/hosts" line="{{ hostvars[item]['floating_ip'] }} {{ hostvars[item]['inventory_hostname'] }}"
      with_items:
        - "{{ groups.masters }}"
        - "{{ groups.lb }}"
